console.log('hola');
//   var word= form.ahorcado.value
  var alfabeto = ("a","b","c","d","e","f","g","h","i","j","k","l","m","n","ñ","o","p"
,"q","r","s","t","u","v","w","x","y","z")
function palabra(form){
  var cohete =("c", "o", "h", "e", "t", "e")
  var bomba = "b", "o", "m", "b", "a"
  var explocion ="e", "x", "p", "l", "o", "c", "i", "o", "n"
  var cuidado = "c", "u", "i", "d", "a", "d" ,"o"
  var alerta = "a", "l", "e", "r", "t", "a"
  var mundo = "m", "u" ,"n", "d", "o"
  var catastrofe = "c", "a", "t", "a", "s", "t", "r", "o", "f", "e"
  var planeta = "p" "l" "a" "n" "e" "t" "a"
  var vida ="v" "i" "d" "a"
  var muerte ="m" "u" "e" "r" "t" "e"
  var salvar="s" "a" "l" "v" "a" "r"
  var ayudar= "a" "y" "u" "d" "a" "r"
  var destruccion="d" "e" "s" "t" "r" "u" "c" "c" "i" "o" "n"
  var guerra = "g" "u" "e" "r" "r" "a"
  var devastacion = "d" "e" "v" "a" "s" "t" "a" "c" "i" "o" "n"
}
function letra (form){
  console.log();
}
